# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/osx-64/_nb_ext_conf-0.4.0-py36_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/anaconda-client-1.6.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/appnope-0.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/asn1crypto-0.22.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/blas-1.0-mkl.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/bleach-1.5.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/bzip2-1.0.7-h1de35cc_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/cairo-1.14.12-hc4e6be7_4.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/certifi-2016.2.28-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/cffi-1.10.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/click-7.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/clyent-1.2.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/cryptography-1.8.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/decorator-4.1.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/entrypoints-0.2.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/ffmpeg-4.0-h01ea3c9_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/flask-1.0.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/fontconfig-2.13.0-h5d5b041_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/freetype-2.9.1-hb4e5f40_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/gettext-0.19.8.1-h15daf44_3.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/glib-2.56.2-hd9629dc_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/graphite2-1.3.13-h2098e52_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/harfbuzz-1.8.8-hb8d4a28_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/hdf5-1.8.20-hfa1e0ec_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/html5lib-0.999-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/icu-58.2-h4b95b61_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/idna-2.6-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/ipykernel-4.6.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/ipython-6.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/ipython_genutils-0.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/ipywidgets-6.0.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/itsdangerous-1.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/jasper-2.0.14-h636a363_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/jedi-0.10.2-py36_2.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/jinja2-2.10.1-py36_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jpeg-9b-he5867d9_2.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/jsonschema-2.6.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/jupyter_client-5.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/jupyter_core-4.3.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libcxx-4.0.1-hcfea43d_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libcxxabi-4.0.1-hcfea43d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libedit-3.1.20181209-hb402a30_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libffi-3.2.1-h475c297_4.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libgfortran-3.0.1-h93005f0_2.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libiconv-1.15-hdd342a3_7.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libopencv-3.4.2-h0d3447a_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libopus-1.3-h1de35cc_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libtiff-4.0.10-hcb84e12_2.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libvpx-1.7.0-h378b8a2_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/libxml2-2.9.9-hf6e021a_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/markupsafe-1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/mistune-0.7.4-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/mkl-2017.0.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nb_anacondacloud-1.4.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nb_conda-2.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nb_conda_kernels-2.1.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nbconvert-5.2.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nbformat-4.4.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/nbpresent-3.0.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/ncurses-6.1-h0a44026_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/notebook-5.0.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/numpy-1.13.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/olefile-0.46-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/opencv-3.4.2-py36h40b0b35_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/openssl-1.0.2l-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/packaging-16.8-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pandocfilters-1.4.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/path.py-10.3.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/pcre-8.43-h0a44026_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pexpect-4.2.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pickleshare-0.7.4-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/pillow-6.0.0-py36hb68e598_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pip-9.0.1-py36_1.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/pixman-0.38.0-h1de35cc_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/prompt_toolkit-1.0.15-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/ptyprocess-0.5.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/py-opencv-3.4.2-py36h0d3447a_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pycparser-2.18-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pygments-2.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pyopenssl-17.0.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pyparsing-2.2.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pysocks-1.6.6-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/python-3.6.3-hc655967_3.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/python-dateutil-2.6.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pytz-2017.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pyyaml-3.12-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/pyzmq-16.0.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/readline-7.0-h1de35cc_5.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/requests-2.14.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/setuptools-36.4.0-py36_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/simplegeneric-0.8.1-py36_1.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/six-1.10.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/sqlite-3.28.0-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/terminado-0.6-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/testpath-0.3.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/tk-8.6.8-ha441bb4_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/tornado-4.5.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/traitlets-4.3.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/urllib3-1.21.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/wcwidth-0.1.7-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/noarch/werkzeug-0.15.4-py_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/wheel-0.29.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/widgetsnbextension-3.0.2-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/xz-5.2.4-h1de35cc_4.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/yaml-0.1.6-0.tar.bz2
https://repo.continuum.io/pkgs/free/osx-64/zlib-1.2.11-0.tar.bz2
https://repo.continuum.io/pkgs/main/osx-64/zstd-1.3.7-h5bba6e5_0.tar.bz2
